spring:
  application:
    name: api-movies-example

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_BASE:movies}
      auto-index-creation: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: env, health, info, loggers

logging.level:
  org.springframework.data.mongodb.core.MongoTemplate: DEBUG
